f_name = "name:firstName"
l_name = "name:lastName"
phone = "name:phone"
email = 'xpath://*[@id="userName"]'
address = "name:address1"
city = "name:city"
state = "name:state"
p_code = "name:postalCode"
country = "name:country"
username = 'xpath://*[@id="email"]'
password = 'xpath://input[@name="password"]'
confirmpassword = 'name:confirmPassword'
submit = "name:submit"